baseURL = 'https://logosblog.com/'
languageCode = 'zh-cn'
title = 'ğ“›ğ“¸ğ“°ğ“¸ğ“¼'
theme = 'hugo-book'

# å¯ç”¨ Emoji
enableEmoji = true


# Hugo-Book ä¸»é¢˜é…ç½®
[params]
  # ä¸»é¢˜é¢œè‰²ï¼šlight, dark, auto
  BookTheme = "light"
  
  #å³ä¾§ç›®å½•
  BookToC = true


# Markdown é…ç½®
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
	  # å…è®¸ HTML
      unsafe = true  
  
  [markup.highlight]
	# ä»£ç é«˜äº®ä¸»é¢˜,å¯é€‰ï¼šmonokai, dracula, github, vim ç­‰
    style = "monokai"  
	# æ˜¾ç¤ºä»£ç è¡Œå·
    lineNos = true